apiVersion: v1
kind: Service
metadata:
  name: backend-despachos-service
  namespace: despachos-app
spec:
  type: ClusterIP
  selector:
    app: backend-despachos
  ports:
    - port: 8081
      targetPort: 8081
